config/routes.rb
Rapidnomadic2::Application.routes.draw do

  get "games/index"

  get "games/show"

 resources :user_info
  resources :friendships
  resources :messages

  match '/accept_friend' => 'friendships#accept'
  get 'profiles/:username' => 'users#profile'
  get "/dashboard" => 'pages#dashboard'

  match 'like/post/:post_id' => 'posts#like', :as => 'like_post'
  match 'unlike/post/:post_id' => 'posts#unlike', :as => 'unlike_post'
  match 'dislike/post/:post_id' => 'posts#dislike', :as => 'dislike_post'
  match 'share/post/:post_id' => 'posts#share', :as => 'share_post'
  get "/world_wall"  => 'pages#world_wall'

  get "/friend_activity"   => 'pages#friend_activity'

  resources :sessions

  post 'photos/:photo_id/comments' => 'comments#create', :as => 'photo_comments'

  scope '/photos/:id' do
    resources :comments, :except => :new
    get '/change' => 'photos#change', :as => 'change_photo'
    get '/photos/:id/comments/new' => 'comments#new', :as => 'new_photo_comment'

  end
  resources :posts do
    resources :comments
  end
    resources :photos #, :except => [:show, :edit, :update]
  resources :comments
  resources :users, :except => :show do
    resources :posts
end

  resources :password_resets

  get 'register' => 'users#new', :as => 'register'

  get 'login' => 'sessions#new', :as => 'login'

  get 'logout' => 'sessions#destroy', :as => 'logout'

   root :to => 'pages#world_wall'

  match '/:username' => 'users#wall', as: 'profile'
  match '/messcount/:user/:friend' => 'messages#count'
  match '/:username/messages' => 'messages#show', as: 'user_messages'
  match '/:username/messages/:friend' => 'messages#show', as: 'user_messages'
  match '/:username/info' => 'user_info#index', as: 'show_user_info'
  match '/:username/friends' => 'friendships#show', as: 'show_friends'
  match '/:username/photos' => 'photos#index', as: 'user_photos'
end

app/views/shared/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<a class="brand" href="<%=	 root_url %>"><%=	 image_tag 'logo_opt.gif', :mouseover => 'logohover_opt.png', :width => '50px', :height => '40px' %><%=	 image_tag 'Untitled-2letters_opt.png', height: '40px' %></a>

    <%=	 form_tag posts_path, method: :get, :style => "display:inline;", :class => 'navbar-form pull-left', :id => 'post_search_form' do %>
        <%=	 text_field_tag :search, params[:search], style: 'background-color:transparent;color: white;border:none;', :placeholder => 'Search...' %>
        <a href="#" onclick="
       _('post_search_form').submit();
                return false;
        ">
          <i class="icon-search icon-white icon-large" style="color: #ffffff;line-height: normal;"></i>
        </a>
        <%=	 submit_tag "", name: nil, :style => "background-color:transparent;border:none;padding:10px;margin:0;", class: 'icon-search icon-white' %>

    <%	end %>
	<ul class="nav">
	  <li>
		<%= link_to 'World Wall', :controller => 'pages', :action => 'world_wall' %>
	  </li>
	  <li><a href="#">Dashboard</a></li>
	  <li><a href="#">ComeToChat</a></li>
	  <li>
		<%= link_to "Games", :controller => 'games', :action => 'index' %>
	  </li>
	</ul>

	<ul class="nav pull-right">
	  <% if current_user %>

		  <li class="dropdown"><a href="#" id="menubar_drop" role="button" class="dropdown-toggle" data-toggle="dropdown"><%=  image_tag current_user.avatar_url(:menubar).to_s %> <%=  "#{current_user.full_name}" %><strong style="color: white" class="caret"></strong></a>

			<ul class="dropdown-menu" role='menu'>
			  <li role="presentation"><%=	 link_to 'View My Profile', profile_for(current_user) %></li>

			  <li><%= link_to "Messages", messages_url %></li>
			</ul>

		  </li>
		  <li class="divider-vertical"></li>
		  <li><%=	 link_to 'Log Out', logout_path %></li>
	  <% else %>
		  <li><%=	 link_to 'Register', register_path %></li>
		  <li class="divider-vertical"></li>
		  <li class="dropdown">
			<a  href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Log In <b class="caret"></b></a>
			<div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
			  <%=	 render 'sessions/form' %>
			   <%= link_to 'Forgotten Password?', new_password_reset_path %>
			</div>
		  </li>
	  <% end %>
	</ul>
  </div>
</div>