config/routes.rb
Rapidnomadic2::Application.routes.draw do

  get "games/index"

  get "games/show"

 resources :user_info
  resources :friendships
  resources :messages

  match '/accept_friend' => 'friendships#accept'
  get 'profiles/:username' => 'users#profile'
  get "/dashboard" => 'pages#dashboard'

  match 'like/post/:post_id' => 'posts#like', :as => 'like_post'
  match 'unlike/post/:post_id' => 'posts#unlike', :as => 'unlike_post'
  match 'dislike/post/:post_id' => 'posts#dislike', :as => 'dislike_post'
  match 'share/post/:post_id' => 'posts#share', :as => 'share_post'
  get "/world_wall"  => 'pages#world_wall'

  get "/friend_activity"   => 'pages#friend_activity'

  resources :sessions

  post 'photos/:photo_id/comments' => 'comments#create', :as => 'photo_comments'

  scope '/photos/:id' do
    resources :comments, :except => :new
    get '/change' => 'photos#change', :as => 'change_photo'
    get '/photos/:id/comments/new' => 'comments#new', :as => 'new_photo_comment'

  end
  resources :posts do
    resources :comments
  end
    resources :photos #, :except => [:show, :edit, :update]
  resources :comments
  resources :users, :except => :show do
    resources :posts
end

  resources :password_resets

  get 'register' => 'users#new', :as => 'register'

  get 'login' => 'sessions#new', :as => 'login'

  get 'logout' => 'sessions#destroy', :as => 'logout'

   root :to => 'pages#world_wall'

  match '/:username' => 'users#wall', as: 'profile'
  match '/messcount/:user/:friend' => 'messages#count'
  match '/:username/messages' => 'messages#show', as: 'user_messages'
  match '/:username/messages/:friend' => 'messages#show', as: 'user_messages'
  match '/:username/info' => 'user_info#index', as: 'show_user_info'
  match '/:username/friends' => 'friendships#show', as: 'show_friends'
  match '/:username/photos' => 'photos#index', as: 'user_photos'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :privacy, :user_id, :description, :image
  has_attached_file :image, :styles => { :profile => ["150x150", :jpg], :orig => "800x800" }
  belongs_to :user
  has_many :comments, :as => :commentable
  validates_attachment_content_type :image,
  :content_type => ['image/jpeg', 'image/pjpeg',
                                   'image/jpg', 'image/png', 'image/tif', 'image/gif'], :message => "has to be in a proper format"
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout 'profile', only: :index
  def index
    @user = User.find_by_username(params[:username])
    @user_info = @user.user_info
  end
  def new
   @photo = Photo.new(:user_id => current_user.id)
  end
  def change
    @photo = Photo.find(params[:id])
  end
   def show
      @photo =c Photo.find(params[:id])
      @comment = Comment.new
      @commentable = @photo
      @comments = @commentable.comments
   end
  def update
   @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
          redirect_to controller: 'photos', action: 'show', id: @photo.id
    else
    render 'edit'
    end
  end
  def destroy
    @user = User.find_by_username(params[:username])
    if @user == current_user
      @photo = Photo.find(params[:id])
      if @photo.destroy
        redirect_to request.referrer
      end
    end
  end
  def create
       @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to profile_url(current_user.username)
    end




  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/change.html.erb
<div class="row">

<div class="span4">
<%=	 simple_form_for @photo , :html => { :multipart => true } do |f| %>
    <%=	 f.hidden_field :user_id %>
    <p><%=	 f.input :name %> </p>
     <p><%= f.input :image %></p>

    
    <p><%=	 f.input :description, :html => { :cols => 15 ,  :rows => 40 } %></p>
    <p><%=	 f.submit 'Change Photo', :class => 'btn btn-success' %></p>
<%	 end %>
</div>

</div>

app/views/photos/edit.html.erb
          <%=	 @photo.name %>
            <div class="span4">
             
            </div>
<%=	 simple_form_for @photo, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
    <%=	 f.hidden_field :user_id %>
    <p><%=	 f.input :name %> </p>
    <p>  <%=	 f.input :image %></p>

  
    <p><%=	 f.input :description, :as => :text, :input_html => { :cols => 15 ,  :rows => 40 } %></p>
    <p><%=	 f.submit 'Change Photo', :class => 'btn btn-success' %></p>
<%	 end %>

app/views/photos/index.html.erb
<% title @user.full_name.to_s + "'s Photos" %>

<ul class="nav nav-tabs" id ="profile_sidebar" style="margin: 0 auto;">
  <li>
    <%= link_to 'Wall', profile_for(@user) %>
  </li>
  <li>
    <%= link_to 'Info', info_for(@user) %>
  </li>
  <li>
    <%= link_to 'Friends', friends_for(@user) %>
  </li>
  <li  class="active">
    <%= link_to 'Photos', photos_for(@user) %>
  </li>
  <li>
    <%= link_to 'Videos', '#' %>
  </li>
  <li>
    <%= link_to 'Quotes', '#' %>
  </li>
</ul>


  <%= simple_form_for Photo.new , :html => { :multipart => true } do |f| %>
      <%#  f.hidden_field :user_id %>
      <p> <%#  f.input :name %></p>

      <p><input id="photo_image" multiple="multiple" name="photo[image]" type="file">

        <%# f.file_field :image, multiple: true, name: 'photo[image]' %></p>
      <p><%#   f.input :description, :as => :text, :input_html => { :cols => 15 ,  :rows => 40 } %></p>
      <p><%=   f.submit 'Add Photo', :class => 'btn btn-success' %></p>
  <% end %>
  <%=  link_to 'Add Photo', controller: 'photos', action: 'new' %> <br/>
  <% @user.photos.each do |photo|  %>
      <div class="photo">
        <%= link_to (image_tag photo.image.url(:medium)) , photo if photo.image %>
      </div>
  <%   end %>

app/views/photos/new.html.erb
<h1>New Photo for <%= current_user.full_name %></h1>
<%=	 simple_form_for @photo, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
    <%=	 f.hidden_field :user_id %>
    <p> <%=	 f.input :name %></p>
 <p><input id="photo_image" multiple="multiple" name="photo[image]" type="file"></p>
    <p><%=	 f.input :description, :as => :text, :input_html => { :cols => 15 ,  :rows => 40 } %></p>
    <p><%=	 f.submit 'Add Photo', :class => 'btn btn-success' %></p>
<%	 end %>

app/views/photos/show.html.erb
<h2><%=	 @photo.name %></h2>
  <%=	 link_to 'Edit Photo' , action: 'change', controller: 'photos', :id => @photo.id %>  <%=	 link_to 'Delete Photo' , photo_path(@photo), :method => 'delete' %>

<%= image_tag @photo.image(:orig).to_s %>

<div class='span4'>
 <p><b><%=	 link_to @photo.user.full_name, :controller => 'users', :action => 'show', :username => @photo.user.username %></b>
   <%= @photo.description %>

  <div id="comments-box">
  
    <h2>Comments</h2>
   <%	 post.comments.each do |comment| %>
        <% if post.comments.first == comment %>
            <div class="comment-first">
        <%	 else %>
            <div class="comment">

        <% end %>
        <%=	link_to comment.commentable.user.full_name, :controller => 'users', :action => 'show', :username => comment.commentable.user.username %> <%=	 comment.content %>
        </div>
        <%	 end %>

    <p>
   <% if current_user %>
          <%=	 render 'comments/form' %>
 <% else %>
 <%=	link_to 'Log in', login_path  %> or   <%=	link_to 'Register', register_path  %>  to add a comment
 <% end %>
 </p>
  </div>



</div>