config/routes.rb
Rapidnomadic2::Application.routes.draw do

  get "games/index"

  get "games/show"

 resources :user_info
  resources :friendships
  resources :messages

  match '/accept_friend' => 'friendships#accept'
  get 'profiles/:username' => 'users#profile'
  get "/dashboard" => 'pages#dashboard'

  match 'like/post/:post_id' => 'posts#like', :as => 'like_post'
  match 'unlike/post/:post_id' => 'posts#unlike', :as => 'unlike_post'
  match 'dislike/post/:post_id' => 'posts#dislike', :as => 'dislike_post'
  match 'share/post/:post_id' => 'posts#share', :as => 'share_post'
  get "/world_wall"  => 'pages#world_wall'

  get "/friend_activity"   => 'pages#friend_activity'

  resources :sessions

  post 'photos/:photo_id/comments' => 'comments#create', :as => 'photo_comments'

  scope '/photos/:id' do
    resources :comments, :except => :new
    get '/change' => 'photos#change', :as => 'change_photo'
    get '/photos/:id/comments/new' => 'comments#new', :as => 'new_photo_comment'

  end
  resources :posts do
    resources :comments
  end
    resources :photos #, :except => [:show, :edit, :update]
  resources :comments
  resources :users, :except => :show do
    resources :posts
end

  resources :password_resets

  get 'register' => 'users#new', :as => 'register'

  get 'login' => 'sessions#new', :as => 'login'

  get 'logout' => 'sessions#destroy', :as => 'logout'

   root :to => 'pages#world_wall'

  match '/:username' => 'users#wall', as: 'profile'
  match '/messcount/:user/:friend' => 'messages#count'
  match '/:username/messages' => 'messages#show', as: 'user_messages'
  match '/:username/messages/:friend' => 'messages#show', as: 'user_messages'
  match '/:username/info' => 'user_info#index', as: 'show_user_info'
  match '/:username/friends' => 'friendships#show', as: 'show_friends'
  match '/:username/photos' => 'photos#index', as: 'user_photos'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :commentable
  #acts_as_commentable
  acts_as_votable
  attr_accessible :content, :whose_wall, :created_at
  define_index do
    indexes content
    indexes comments.content, as: :comment_content
    indexes [user.first_name, user.last_name], as: :user_name
    set_property :delta => true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout '3col'
include ApplicationHelper
  def new
   @new_post  = current_user.posts.build

  end
  def index

    if params[:search]
      @posts = Post.search(params[:search], page: 1, per_page: 20)
    end

  end
   def dislike
     @post = Post.find(params[:post_id])
     current_user.dislikes @post
     redirect_to request.referrer
   end
  def unlike
    @post = Post.find(params[:post_id])
    current_user.unlike @post
    redirect_to profile_for(@post.user)
  end
  def share
    @post = Post.find(params[:post_id])

    @shared_post = current_user.posts.build(content: @post.content, whose_wall: current_user.id)
    if @shared_post.save
      redirect_to profile_for(current_user)
    end
  end
  def like
    @post = Post.find(params[:post_id])
    current_user.likes @post
    redirect_to request.referrer
  end
  def create

  	@post = current_user.posts.build(params[:post])
  	if @post.content.to_s.strip.length == 0
      flash[:notice] = 'Write something in your post first!'
      redirect_to request.referrer
    else
      @post.created_at = Time.now
      if @post.save
        respond_to do |format|
          format.html { redirect_to request.referrer }
          format.js { render 'users/post' }
        end

      else
        flash[:notice] = 'Post could\'nt be saved'
        redirect_to request.referrer
      end

  end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div id="post_form">

  <%=	 form_for (@new_post)  , remote: true  do |f| %>
      <%= f.hidden_field :whose_wall, :value => @user.id %>
      <%=	 f.text_area :content, :placeholder => 'How are you doing?' %>
      <%=	 f.submit "POST", :id => 'post_but', :class => 'btn btn-info' %>
  <%	 end %>
</div>

app/views/posts/_post.html.erb
<li
<% if @all_posts.first == post %>
class="first"
<% end %>
>
  <%= image_tag post.user.avatar_url(:thumb).to_s, :width => 80, :height => 80  if post.user  %>
  <%=h link_to post.user.full_name, :controller => 'users', :action => 'wall', :username => post.user.username  if post.user %>
  <span style="float: right">
   <span class="time-box"> <%= time_ago_in_words(post.created_at).gsub('about','') + ' ago' %></span>

   <table class="interactions-tbl">
     <tr>
       <td>
     <% if current_user %>
         <% if current_user.liked? post %>
            <%=	 link_to 'Unlike', {:controller => :posts, action: 'unlike', :post_id => post.id }, {:id => 'like_post_'+post.id.to_s } %>

         <% else %>
            <span class="like-group" id="like-group-post-<%= post.id %>" >
          <a href="<%= like_post_path(:post_id => post.id) %>" data-toggle="popover" data-placement="left" data-trigger='hover' class="popover-but" title="Like"><i class="icon-thumbs-up icon-large"></i></a>
            <%#	 link_to '', {:controller => :posts, action: 'like', :post_id => post.id }, {:id => 'like_post_'+post.id.to_s } %>
</span>
     <% end %>
     <% end %>
       </td>


    <td style="border-left: 1px solid black;
            border-right: 1px solid black;">
      <!--<a href="#"  data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." data-trigger='hover' class="btn popover-but" data-original-title="Popover on top">Popover on top</a>   -->
      <a href="<%= dislike_post_path(:post_id => post.id) %>" data-toggle="popover" data-trigger='hover' class="popover-but" title="Dislike"><i class="icon-thumbs-down icon-large"></i></a>
</td>
       <td>
         <a href="<%= share_post_path(:post_id => post.id) %>" ><i class="icon-share icon-search"></i></a>
       </td>
        <%#	 link_to 'Dislike', {:controller => :posts, action: 'dislike', :post_id => post.id } %>
 </tr>
     <tr><td colspan="100%" >
  <%=	 pluralize(post.likes.size, "like") %></td>
       <% if post.dislikes.size != 0 %>
           <td>
             <%=	 pluralize(post.dislikes.size, "like") %>
           </td>
       <% end %>

       <script type="text/javascript">
           $('.popover-but').popover();
       </script>
</tr>
     <tr>
       <td colspan="100%"><a href="#" class="showCommentsLink" id="post-<%= post.id.to_s %>-comment-link" onclick="

    if (_('comment-box-<%= post.id.to_s %>').style.display == 'none')
            {
                    var minus ='<i class=\'icon-minus\'></i>';
               $('#post-<%= post.id.to_s %>-comment-link').html(minus + ' Comments')
     _('comment-box-<%= post.id.to_s %>').style.display = 'block'
               }
               else {
            var plus = '<i class=\'icon-plus\'></i>';
            $('#post-<%= post.id.to_s %>-comment-link').html(plus+'Comments');
         _('comment-box-<%= post.id.to_s %>').style.display = 'none'

                   }
            return false;
       "><i class='icon-plus'></i>Comments</a> </td>
     </tr>
   </table>
  </span>

       <%#	 image_tag 'twitter/bootstrap/glyphicons-halflings.png' %>

  <div class="post_mess"><%= post.content %></div>
  <% if  post.content.length < 35 %>
      <br/><br/><br/>
  <% end %>
  <div class="comments-box" style="margin-left: 87px;display: none;" id="comment-box-<%= post.id.to_s %>">
    <%	 post.comments.each do |comment| %>
        <% if post.comments.first == comment %>
            <div class="comment-first">
        <%	 else %>
            <div class="comment">

        <% end %>
      <%=	 image_tag comment.user.avatar_url(:menubar).to_s %>  <%=	link_to comment.user.full_name, profile_for(comment.user) %> <%=	 comment.content %>
        </div>
    <%	 end %>

    <p>
   <% if current_user %>
          <%= form_for [post,@comment], :id => post.id.to_s+ '-new-comment'  do |f| %>

           <div class="comment-text-box" style="display: inline;">
             <%=	 f.hidden_field :user_id, :value => current_user.id %>
              <%=	 f.text_area :content, :placeholder => 'Add a Comment...', rows: 1, onKeyPress: '
              if (event.keyCode == 13) {
                   this.form.submit();
                   return false;
               }' %>
            </div>
            <%=	 f.submit 'Add Comment' %>
        <%	 end %>
 <% else %>
 <%=	link_to 'Log in', login_path  %> or   <%=	link_to 'Register', register_path  %>  to add a comment
 <% end %>
 </p>
  </div>
    <script type="text/javascript">
          $('')
    </script>
</li>

app/views/posts/index.html.erb
<h2>All Posts</h2>
<%=	 form_tag posts_path, method: :get do %>
<%=	 text_field_tag :search, params[:search] %>
    <%=	 submit_tag "Search", name: nil %>
<%	end %>
<% if @posts %>
    <div id='posts list'>
    <ul style="list-style-type: none;"><% @posts.each do |p| %>
       <li style="height: 87px;border-radius: 6px;border: 1px solid black;">
         <%= link_to p  do %>
       <div id="post_search_result_<%= p.id %>" style="background-color: white;">
       <%= p.user.full_name %>  <div id='post-<%= p.id %>-content' style="color: #000000;"><%=	 p.content %></div>
        </div>
             <%	 end %>
       </li>
    <%	 end %></ul>
    </div>
<% else %>
    <p>Enter a part of a post to search for it</p>
<% end %>

app/views/posts/show.js.erb
$('#profile_posts').append('<%= j render (@all_posts) %>')         ;

<% if @all_posts.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@all_posts) %>') ;

<% else %>
$('.pagination').text('');

$('.pagination').remove();
<% end %>
<% sleep 1 %>